version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./be
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
  frontend:
    container_name: frontend
    build:
      context: ./fe
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 5173:5173
